# ansible-playbook deploy.yaml -i inventories/dev/hosts --vault-id ~/.tokens/master_id

- hosts: tools
  strategy: free
  roles:
    - common

  tasks:
    - include_role:
        name: common
        tasks_from: make_data_dir

    - name: Ensure subdirectories exist
      file: 
        path: '{{ directory }}'
        state: directory
      loop_control:
        loop_var: directory
      loop:
        - '{{ data_dir }}/pihole/'
        - '{{ data_dir }}/dnsmasq/'

    - include_role:
        name: docker
        tasks_from: stack_deploy

    - name: Ensure open ports
      ufw:
        rule: allow
        port: '{{ port }}'
        proto: any
      become: yes
      loop_control:
        loop_var: port
      loop:
        - '53'
        - '67'

    - name: Reload Firewall and enable at boot
      ufw:
        state: enabled
        policy: deny
      become: yes
